feat: put commands in action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -45,7 +45,7 @@ inputs:
 
   # `semantic-release version` command line options
   prerelease:
-    type: string
+    type: boolean
     required: false
     description: |
       Force the next version to be a prerelease. Set to "true" or "false".
@@ -65,20 +65,20 @@ inputs:
       one of "prerelease", "patch", "minor", or "major".
 
   commit:
-    type: string
+    type: boolean
     required: false
     description: Whether or not to commit changes locally. Defaults are handled
       by python-semantic-release internal version command.
 
   tag:
-    type: string
+    type: boolean
     required: false
     description: |
       Whether or not to make a local version tag. Defaults are handled
       by python-semantic-release internal version command.
 
   push:
-    type: string
+    type: boolean
     required: false
     description: |
       Whether or not to push local commits to the Git repository. See
@@ -86,19 +86,19 @@ inputs:
       for how the default is determined between push, tag, & commit.
 
   changelog:
-    type: string
+    type: boolean
     required: false
     description: |
       Whether or not to update the changelog.
 
   vcs_release:
-    type: string
+    type: boolean
     required: false
     description: |
       Whether or not to create a release in the remote VCS, if supported
 
   build:
-    type: string
+    type: boolean
     required: false
     description: |
       Whether or not to run the build_command for the project. Defaults are
@@ -140,6 +140,7 @@ runs:
     #   shell: bash
     - name: Prepare PSR environment
       run: |
+        set -ex
         if ! command -v python $> /dev/null
         then
           echo "Python not found."
@@ -154,7 +155,92 @@ runs:
           pip install "python-semantic-release==$INPUT_PSR_VERSION"
         fi
       shell: bash
-    - name: Launch PSR action script
-      run: ./action.sh
+    - name: PSR action script
       id: semrel
       shell: bash
+      run: |
+        export PSR_ARGS=""
+        force_levels=("prerelease" "patch" "minor" "major")
+        if [ -z "$INPUT_FORCE" ]; then
+          true # do nothing if 'force' input is not set
+        elif
+          echo '%s\0' "${force_levels[@]}" | grep -Fxzq "$INPUT_FORCE"
+        then
+          ARGS+=("--$INPUT_FORCE")
+        else
+          echo "Error: Input 'force' must be one of: %s" >&2
+          echo "${force_levels[@]}" >&2
+        fi
+
+        if [ -n "$INPUT_BUILD_METADATA" ]; then
+              ARGS+=("--build-metadata $INPUT_BUILD_METADATA")
+        fi
+
+        if [ -n "$INPUT_PRERELEASE_TOKEN" ]; then
+              ARGS+=("--prerelease-token $INPUT_PRERELEASE_TOKEN")
+        fi
+
+        # Change to configured directory
+        cd "${INPUT_DIRECTORY}"
+
+        # Set Git details
+        if ! [ "${INPUT_GIT_COMMITTER_NAME:="-"}" = "-" ]; then
+          git config user.name "$INPUT_GIT_COMMITTER_NAME"
+        fi
+        if ! [ "${INPUT_GIT_COMMITTER_EMAIL:="-"}" = "-" ]; then
+          git config user.email "$INPUT_GIT_COMMITTER_EMAIL"
+        fi
+        if (
+          [ "${INPUT_GIT_COMMITTER_NAME:="-"}" != "-" ] &&
+          [ "${INPUT_GIT_COMMITTER_EMAIL:="-"}" != "-" ]
+          );
+        then
+          # Must export this value to the environment for PSR to consume the override
+          export GIT_COMMIT_AUTHOR="$INPUT_GIT_COMMITTER_NAME <$INPUT_GIT_COMMITTER_EMAIL>"
+        fi
+
+        # See https://github.com/actions/runner-images/issues/6775#issuecomment-1409268124
+        # and https://github.com/actions/runner-images/issues/6775#issuecomment-1410270956
+        # git config --system --add safe.directory "*"
+
+        if (
+          [[n "$INPUT_SSH_PUBLIC_SIGNING_KEY" &&
+          -n "$INPUT_SSH_PRIVATE_SIGNING_KEY" ]]
+        );
+        then
+          echo "SSH Key pair found, configuring signing..."
+
+          # Write keys to disk
+          mkdir -vp ~/.ssh
+          echo -e "$INPUT_SSH_PUBLIC_SIGNING_KEY" >>~/.ssh/signing_key.pub
+          cat ~/.ssh/signing_key.pub
+          echo -e "$INPUT_SSH_PRIVATE_SIGNING_KEY" >>~/.ssh/signing_key
+          # DO NOT CAT private key for security reasons
+          sha256sum ~/.ssh/signing_key
+          # Ensure read only private key
+          chmod 400 ~/.ssh/signing_key
+
+          # Enable ssh-agent & add signing key
+          eval "$(ssh-agent -s)"
+          ssh-add ~/.ssh/signing_key
+
+          # Create allowed_signers file for git
+          if [ "${INPUT_GIT_COMMITTER_EMAIL:="-"}" = "-" ]; then
+                  echo >&2 "git_committer_email must be set to use SSH key signing!"
+                  exit 1
+          fi
+          touch ~/.ssh/allowed_signers
+          echo "$INPUT_GIT_COMMITTER_EMAIL $INPUT_SSH_PUBLIC_SIGNING_KEY" >~/.ssh/allowed_signers
+
+          # Configure git for signing
+          git config gpg.format ssh
+          git config gpg.ssh.allowedSignersFile ~/.ssh/allowed_signers
+          git config user.signingKey ~/.ssh/signing_key
+          git config commit.gpgsign true
+          git config tag.gpgsign true
+        fi
+
+        # Copy inputs into correctly-named environment variables
+        export GH_TOKEN="${INPUT_GITHUB_TOKEN}"
+
+        semantic-release $INPUT_ROOT_OPTIONS version ${ARGS[*]}"
